[features]
seeds = false
[programs.localnet]
solana_twitter = "D3YdyXTsbpeUcjp5hUU6YVgAUxq7VXADtCUqRkrsW7tG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/callummcintyre/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
